site_name: 洛曦AI文档
repo_url: https://github.com/Ikaros-521/LX_AI
repo_name: 洛曦AI

theme:
  name: material
  language: zh
  favicon: static/images/favicon.png
  icon:
    logo: fontawesome/solid/dove
  features:
    - navigation.instant
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  palette:
    scheme: default
    primary: blue

docs_dir: 'docs'
site_dir: 'site'

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: false
  analytics:
    provider: google
    property: G-FR32RDV2MT

copyright: >
  Copyright &copy; 2025 <a href="https://github.com/Ikaros-521/LX_AI">洛曦AI</a> & Ikaros-521

nav:
  - 首页: index.md
  - 安装: install.md
  - 使用&功能讲解:
    - 基础功能: features/basic.md
    - 平台: features/platform.md
    - 大语言模型: features/llm.md
    - 文本转语音: features/tts.md
    - 虚拟身体: features/visual_body.md
    - 其他: features/other.md
  - 常见问题: faq.md
  - 更新日志: changelog.md
  - 关于: about.md